### ISSUE TITLE
Why VALUE was removed in 2.0.0

### ISSUE THREAD

**Issue by syabro** [handsontable/formula.js#9]
https://github.com/handsontable/formula.js/commit/310b666063fc222c1a1b603557a7ff0a87f9b409

**Comment by swistach** [comment]
Hi @syabro, I've removed incorrect/incomplete implementation.
Moreover, `numbro.js` is no longer required.

**Comment by syabro** [comment]
@swistach what should I use instead of VALUE then? I need to convert strings to numbers :(

**Comment by swistach** [comment]
Could you try using [`NUMBERVALUE`](https://github.com/handsontable/formula.js/blob/develop/lib/text.js#L149)?

Besides, there are formulas `INT` or` ROUND`. They convert text into a number using [`utils.parseNumber`](https://github.com/handsontable/formula.js/blob/develop/lib/utils.js#L105) function.

**Comment by syabro** [comment]
Sure, but it's not included in supported formulas in https://github.com/handsontable/formula-parser/blob/develop/src/supported-formulas.js
Are all formulas from `formula.js` supported or only listed in `supported-formulas.js`?

**Comment by swistach** [comment]
You're right. Fortunately, you can overwrite it as in the example: http://jsfiddle.net/9r1cq0e6/

**Comment by syabro** [comment]
@swistach thanks, will try
